-- PitchIQ — MongoDB Document Model Reference
-- This file is documentation only. The database is now MongoDB (PyMongo).
-- Collection: analysis_sessions
--
-- Document structure:
-- {
--   _id:             ObjectId  (auto)
--   session_token:   string    UUID, unique index
--   player_name:     string    default "Anonymous"
--   player_age:      int
--   created_at:      datetime  UTC, descending index
--
--   pace:            int  1-99
--   shooting:        int  1-99
--   passing:         int  1-99
--   dribbling:       int  1-99
--   defending:       int  1-99
--   physical:        int  1-99
--   stamina:         int  1-99
--   strength:        int  1-99
--   agility:         int  1-99
--   vision:          int  1-99
--
--   predictions:     array   [{position, confidence}, ...]
--   gap_analysis:    object  {position, gaps, strengths, weaknesses}
--   training_plan:   object  {drills, weekly_plan, ...}
--   cluster_info:    object  {cluster_id, cluster_size, ...}
--   scouting_report: string  AI-generated plain-text report (nullable)
-- }
--
-- Indexes:
--   session_token  (unique)
--   created_at     (descending)
